### ISSUE TITLE
legenda de ícones das categorias

### ISSUE THREAD

**Issue by cadu-leite** [zokis/TG#10]
Adicionar um botão para mostrar a legenda de pontos das categorias de ocorrências.

**Comment by zokis** [comment]
4d7c091443d8abae6ebcd9d657fa7366ce62d946
a78aaf01d6088ff7b4708bbe737107ea5027033f
7fa436cc7857cff81cc53eb41be56f7380bfaec2
551a4d2c6bd38a40c1d9bfaee1d954cba52657bb
